######################################
### ROS-Sensors Dependent Services ###
######################################
# Example
- name: ros-sensor-example
  description: Example Services
  parent: ros-sensors.service
  catkin_ws: /home/qcr/qcr_agilex_payload_ws/devel/setup.bash
  command: echo Started Example ROS-Sensors Dependent Service
  enabled: True
  restart: True
  restart_after: 5

  
####################################
### ROS-Robot Dependent Services ###
####################################
# Example
- name: ros-robot-example
  description: Example Services
  parent: ros-robot.service
  catkin_ws: /home/qcr/qcr_agilex_payload_ws/devel/setup.bash
  command: echo Started Example ROS-Robot Dependent Service
  enabled: True
  restart: True
  restart_after: 5

  
######################################
### ROS-Project Dependent Services ###
######################################
# Example
- name: ros-project-example
  description: Example Services
  parent: ros-project.service
  catkin_ws: /home/qcr/qcr_agilex_payload_ws/devel/setup.bash
  command: echo Started Example ROS-Project Dependent Service
  enabled: True
  restart: True
  restart_after: 5